//! End-to-end tests of the binary: exit codes, generated bytes, and the
//! identities git actually resolves. Every command runs against a scratch
//! HOME, so the developer's real gitconfig is never read or written.
//!
//! The unit tests cover the pieces. These cover the claim the pieces exist to
//! make: that after `apply`, the installed git resolves the identity the
//! config asked for. So they use a real git, real repositories, and real
//! remotes, and assert on what git reports rather than on cloakroom's idea of
//! it. If git changes how it matches, these are the tests that notice.
//!
//! Shape of a test: build a `TempTree`, write a config, run a command, assert
//! on exit code and output. `TempTree` cleans up on drop.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use sha2::{Digest, Sha256};
use tempfile::TempDir;

/// A scratch home directory, removed on drop.
struct TempTree {
    root: TempDir,
}

impl TempTree {
    fn new(name: &str) -> Self {
        let root = tempfile::Builder::new()
            .prefix(&format!("cloakroom-cli-{name}-"))
            .tempdir()
            .unwrap();
        std::fs::create_dir_all(root.path().join("home")).unwrap();
        TempTree { root }
    }

    fn home(&self) -> PathBuf {
        self.root.path().join("home")
    }

    fn config_dir(&self) -> PathBuf {
        self.home().join(".config/cloakroom")
    }

    fn write_config(&self, contents: &str) {
        std::fs::create_dir_all(self.config_dir()).unwrap();
        std::fs::write(self.config_dir().join("config.toml"), contents).unwrap();
    }

    fn read_generated(&self, name: &str) -> String {
        std::fs::read_to_string(self.config_dir().join("generated").join(name)).unwrap()
    }

    fn object_files(&self) -> Vec<PathBuf> {
        let mut paths: Vec<_> = std::fs::read_dir(self.config_dir().join("generated/objects"))
            .unwrap()
            .map(|entry| entry.unwrap().path())
            .collect();
        paths.sort();
        paths
    }

    /// Objects are named by digest, so tests find one by what is in it.
    fn object_containing(&self, needle: &str) -> PathBuf {
        self.object_files()
            .into_iter()
            .find(|path| std::fs::read_to_string(path).unwrap().contains(needle))
            .unwrap()
    }
}

/// Point HOME and XDG_CONFIG_HOME into the tree and silence the system
/// scope, for the cloakroom binary and every git helper alike.
///
/// All five settings matter. GIT_CONFIG_GLOBAL and GIT_CONFIG_SYSTEM are
/// removed because they would override HOME and pull in the developer's real
/// files. GIT_CONFIG_NOSYSTEM drops /etc/gitconfig, which on some machines
/// sets an identity and would make "no identity resolves" tests pass or fail
/// by accident. Anything that runs git without this is reading the real
/// environment.
fn sandbox(command: &mut Command, tree: &TempTree) {
    command
        .env_remove("GIT_CONFIG_GLOBAL")
        .env_remove("GIT_CONFIG_SYSTEM")
        .env("HOME", tree.home())
        .env("XDG_CONFIG_HOME", tree.home().join(".config"))
        .env("GIT_CONFIG_NOSYSTEM", "1");
}

/// Run the binary under test. `cwd` matters: gitdir rules and every report
/// are answered relative to it.
fn cloakroom(tree: &TempTree, cwd: &Path, args: &[&str]) -> Output {
    let mut command = Command::new(env!("CARGO_BIN_EXE_cloakroom"));
    command.args(args).current_dir(cwd);
    sandbox(&mut command, tree);
    command.output().unwrap()
}

/// Run git for test setup or inspection. Asserts success, because this is
/// never the thing under test and a silent failure here would show up as a
/// confusing assertion somewhere else.
fn git(tree: &TempTree, cwd: &Path, args: &[&str]) -> Output {
    let mut command = Command::new("git");
    command.args(args).current_dir(cwd);
    sandbox(&mut command, tree);
    let output = command.output().unwrap();
    assert!(
        output.status.success(),
        "git {args:?} failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    output
}

fn code(output: &Output) -> i32 {
    output.status.code().unwrap()
}

fn stdout(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).into_owned()
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

/// hasconfig includeIf conditions arrived in git 2.36. Tests that need them
/// skip rather than fail on an older git; path rules are the only thing
/// cloakroom promises everywhere.
fn git_supports_hasconfig() -> bool {
    let output = Command::new("git").arg("version").output().unwrap();
    let text = String::from_utf8_lossy(&output.stdout);
    let mut parts = text.trim().rsplit(' ').next().unwrap_or("0.0").split('.');
    let major: u32 = parts.next().and_then(|p| p.parse().ok()).unwrap_or(0);
    let minor: u32 = parts.next().and_then(|p| p.parse().ok()).unwrap_or(0);
    (major, minor) >= (2, 36)
}

/// The standard fixture: two profiles, one of them unused, and both kinds of
/// rule pointing at the other. The unused profile makes pruning testable.
const SAMPLE: &str = r#"[profiles.personal]
name = "Pat Personal"
email = "pat@example.com"

[profiles.work]
name = "Pat Work"
email = "pat@work.example"

[[rules]]
profile = "work"
path = "~/src/work/"

[[rules]]
profile = "work"
remotes = [
  "git@example.com:work/**",
  "https://example.com/work/**",
]
"#;

/// SAMPLE plus a rule for every profile, so doctor has no unused profiles.
/// Used wherever a test asserts on a clean doctor run, or on one specific
/// issue that an unrelated note would obscure.
const SAMPLE_ALL_USED: &str = r#"[profiles.personal]
name = "Pat Personal"
email = "pat@example.com"

[profiles.work]
name = "Pat Work"
email = "pat@work.example"

[[rules]]
profile = "personal"
path = "~/src/personal/"

[[rules]]
profile = "work"
path = "~/src/work/"
"#;

/// The exact bytes SAMPLE's work profile must compile to. Spelled out rather
/// than produced by the renderer, so a change to the output format has to be
/// made here as well, deliberately. Git parses these files, so tabs, quoting,
/// and blank lines are all part of the contract.
const GOLDEN_WORK_PROFILE: &str = "# Generated by cloakroom. Do not edit.\n\
# Edit config.toml and run `cloakroom apply` instead.\n\
\n\
[cloakroom]\n\
\tprofile = \"work\"\n\
[user]\n\
\tname = \"Pat Work\"\n\
\temail = \"pat@work.example\"\n";

/// Reimplemented rather than shared with the crate, so the test is an
/// independent statement of the naming scheme instead of an echo of it.
fn digest(contents: &str) -> String {
    let mut hex = String::with_capacity(64);
    for byte in Sha256::digest(contents.as_bytes()) {
        write!(hex, "{byte:02x}").unwrap();
    }
    hex
}

/// The exact root SAMPLE must compile to. Three includes from two rules,
/// because the remote rule emits one per pattern, and all three point at the
/// one work object. The digest is computed, since it is a function of
/// GOLDEN_WORK_PROFILE and writing it out twice would only be a copy.
fn golden_root() -> String {
    let work = digest(GOLDEN_WORK_PROFILE);
    format!(
        "# Generated by cloakroom. Do not edit.\n\
         # Edit config.toml and run `cloakroom apply` instead.\n\
         \n\
         [includeIf \"gitdir:~/src/work/\"]\n\
         \tpath = ./objects/{work}.gitconfig\n\
         [includeIf \"hasconfig:remote.*.url:git@example.com:work/**\"]\n\
         \tpath = ./objects/{work}.gitconfig\n\
         [includeIf \"hasconfig:remote.*.url:https://example.com/work/**\"]\n\
         \tpath = ./objects/{work}.gitconfig\n"
    )
}

/// Absolute, not `~/...`: the sandbox sets XDG_CONFIG_HOME, and cloakroom
/// writes an absolute include in that case because git does not expand XDG
/// variables in include paths.
fn expected_include_path(tree: &TempTree) -> String {
    format!(
        "{}/generated/root.gitconfig",
        tree.config_dir().to_str().unwrap()
    )
}

fn global_include_paths(tree: &TempTree) -> Vec<String> {
    let mut command = Command::new("git");
    command
        .args(["config", "--global", "--get-all", "include.path"])
        .current_dir(tree.home());
    sandbox(&mut command, tree);
    let output = command.output().unwrap();
    stdout(&output).lines().map(str::to_owned).collect()
}

/// A real repository at a real path. gitdir conditions match on the location
/// of .git, so a directory alone would not do.
fn repo(tree: &TempTree, relative: &str) -> PathBuf {
    let path = tree.home().join(relative);
    std::fs::create_dir_all(&path).unwrap();
    git(tree, &path, &["init", "--quiet"]);
    path
}

#[test]
fn init_creates_the_tree_and_exactly_one_managed_include() {
    let tree = TempTree::new("init");
    let output = cloakroom(&tree, &tree.home(), &["init"]);
    assert_eq!(code(&output), 0, "stderr: {}", stderr(&output));

    assert!(tree.config_dir().join("config.toml").is_file());
    assert!(tree.config_dir().join("generated/root.gitconfig").is_file());
    assert!(tree.config_dir().join("generated/objects").is_dir());
    assert_eq!(global_include_paths(&tree), [expected_include_path(&tree)]);

    // Re-running must not add a second include or rewrite the config.
    let before = std::fs::read_to_string(tree.config_dir().join("config.toml")).unwrap();
    let output = cloakroom(&tree, &tree.home(), &["init"]);
    assert_eq!(code(&output), 0);
    assert_eq!(global_include_paths(&tree), [expected_include_path(&tree)]);
    let after = std::fs::read_to_string(tree.config_dir().join("config.toml")).unwrap();
    assert_eq!(before, after);
}

#[test]
fn init_keeps_an_edited_config() {
    let tree = TempTree::new("init-keeps");
    tree.write_config(SAMPLE);
    let output = cloakroom(&tree, &tree.home(), &["init"]);
    assert_eq!(code(&output), 0, "stderr: {}", stderr(&output));
    let kept = std::fs::read_to_string(tree.config_dir().join("config.toml")).unwrap();
    assert_eq!(kept, SAMPLE);
    // The edited config was compiled, not the starter.
    assert_eq!(tree.read_generated("root.gitconfig"), golden_root());
}

/// Byte-for-byte output, then a second run that reports only "unchanged".
/// The second half is the real claim: apply is idempotent, so it can be run
/// from a shell hook without rewriting files git may be reading.
#[test]
fn apply_renders_the_golden_bytes_deterministically() {
    let tree = TempTree::new("apply");
    tree.write_config(SAMPLE);
    let output = cloakroom(&tree, &tree.home(), &["apply"]);
    assert_eq!(code(&output), 0, "stderr: {}", stderr(&output));

    assert_eq!(tree.read_generated("root.gitconfig"), golden_root());
    assert_eq!(
        std::fs::read_to_string(tree.object_containing("pat@work.example")).unwrap(),
        GOLDEN_WORK_PROFILE
    );
    assert_eq!(tree.object_files().len(), 2);
    assert!(tree.object_containing("pat@example.com").is_file());

    let output = cloakroom(&tree, &tree.home(), &["apply"]);
    assert_eq!(code(&output), 0);
    assert_eq!(tree.read_generated("root.gitconfig"), golden_root());
    assert_eq!(
        std::fs::read_to_string(tree.object_containing("pat@work.example")).unwrap(),
        GOLDEN_WORK_PROFILE
    );
    // The second run touched nothing.
    for line in stdout(&output).lines() {
        assert!(line.starts_with("unchanged "), "unexpected line: {line}");
    }
}

#[test]
fn apply_prunes_objects_removed_from_the_manifest() {
    let tree = TempTree::new("prune");
    tree.write_config(SAMPLE);
    cloakroom(&tree, &tree.home(), &["apply"]);
    let personal = tree.object_containing("pat@example.com");

    let without_personal = SAMPLE.replace(
        "[profiles.personal]\nname = \"Pat Personal\"\nemail = \"pat@example.com\"\n\n",
        "",
    );
    tree.write_config(&without_personal);
    let output = cloakroom(&tree, &tree.home(), &["apply"]);
    assert_eq!(code(&output), 0, "stderr: {}", stderr(&output));
    assert!(
        stdout(&output).contains(&format!(
            "removed generated/objects/{}",
            personal.file_name().unwrap().to_string_lossy()
        )),
        "stdout: {}",
        stdout(&output)
    );
    assert!(!personal.exists());
}

#[test]
fn apply_rejects_an_invalid_config_with_every_finding() {
    let tree = TempTree::new("invalid");
    tree.write_config(
        "[profiles.a]\nname = \"A\"\nemail = \"a@b\"\n\
         [[rules]]\nprofile = \"ghost\"\npath = \"~/x/\"\n\
         [[rules]]\nprofile = \"a\"\npath = \"~/y/\"\nremotes = [\"git@h:o/**\"]\n",
    );
    let output = cloakroom(&tree, &tree.home(), &["apply"]);
    assert_eq!(code(&output), 2);
    let errors = stderr(&output);
    assert!(errors.contains("unknown profile"), "stderr: {errors}");
    assert!(errors.contains("both path and remotes"), "stderr: {errors}");
}

#[test]
fn apply_requires_a_config() {
    let tree = TempTree::new("apply-missing-config");
    let output = cloakroom(&tree, &tree.home(), &["apply"]);
    assert_eq!(code(&output), 2);
    assert!(stderr(&output).contains("run cloakroom init"));
}

/// Init compiles before it touches the global gitconfig. A config that does
/// not validate must leave git exactly as it was, with no include pointing at
/// a root that was never written.
#[test]
fn init_does_not_install_an_include_for_an_invalid_config() {
    let tree = TempTree::new("init-invalid-config");
    tree.write_config("[[rules]]\nprofile = \"missing\"\npath = \"~/src/\"\n");

    let output = cloakroom(&tree, &tree.home(), &["init"]);
    assert_eq!(code(&output), 2, "stderr: {}", stderr(&output));
    assert!(stderr(&output).contains("unknown profile"));
    assert!(global_include_paths(&tree).is_empty());
}

#[test]
fn status_names_the_profile_for_a_gitdir_match() {
    let tree = TempTree::new("status-gitdir");
    tree.write_config(SAMPLE);
    cloakroom(&tree, &tree.home(), &["init"]);
    let repo = repo(&tree, "src/work/app");

    let output = cloakroom(&tree, &repo, &["status"]);
    assert_eq!(code(&output), 0, "stderr: {}", stderr(&output));
    let report = stdout(&output);
    assert!(report.contains("pat@work.example"), "report: {report}");
    assert!(
        report.contains("profile:    work (selected by cloakroom)"),
        "report: {report}"
    );
}

/// The repository sits nowhere near a path rule, so only the remote can
/// select the profile.
#[test]
fn status_names_the_profile_for_a_remote_match() {
    if !git_supports_hasconfig() {
        return;
    }
    let tree = TempTree::new("status-remote");
    tree.write_config(SAMPLE);
    cloakroom(&tree, &tree.home(), &["init"]);
    let repo = repo(&tree, "elsewhere/app");
    git(
        &tree,
        &repo,
        &["remote", "add", "origin", "git@example.com:work/app.git"],
    );

    let output = cloakroom(&tree, &repo, &["status"]);
    assert_eq!(code(&output), 0, "stderr: {}", stderr(&output));
    let report = stdout(&output);
    assert!(
        report.contains("profile:    work (selected by cloakroom)"),
        "report: {report}"
    );
}

#[test]
fn status_reports_a_foreign_identity_as_no_profile() {
    let tree = TempTree::new("status-foreign");
    tree.write_config(SAMPLE);
    cloakroom(&tree, &tree.home(), &["init"]);
    // A fall-through identity set outside cloakroom's files.
    git(
        &tree,
        &tree.home(),
        &["config", "--global", "user.name", "Pat Global"],
    );
    git(
        &tree,
        &tree.home(),
        &["config", "--global", "user.email", "pat@global.example"],
    );
    let repo = repo(&tree, "elsewhere/app");

    let output = cloakroom(&tree, &repo, &["status"]);
    assert_eq!(code(&output), 0, "stderr: {}", stderr(&output));
    let report = stdout(&output);
    assert!(report.contains("pat@global.example"), "report: {report}");
    assert!(report.contains("profile:    none"), "report: {report}");
}

/// A hand-written cloakroom.profile with a matching identity beside it.
/// Nothing here came from a generated object, so the marker is not trusted
/// and the run exits 1. Without the origin check this would read as clean.
#[test]
fn status_rejects_an_external_profile_marker() {
    let tree = TempTree::new("status-external-marker");
    git(
        &tree,
        &tree.home(),
        &["config", "--global", "cloakroom.profile", "work"],
    );
    git(
        &tree,
        &tree.home(),
        &["config", "--global", "user.name", "Pat Global"],
    );
    git(
        &tree,
        &tree.home(),
        &["config", "--global", "user.email", "pat@global.example"],
    );
    let repo = repo(&tree, "external-marker/app");

    let output = cloakroom(&tree, &repo, &["status"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("identity is overridden"));
}

#[test]
fn status_without_any_identity_exits_one() {
    let tree = TempTree::new("status-none");
    let repo = repo(&tree, "bare/app");
    let output = cloakroom(&tree, &repo, &["status"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("identity:   none"));
}

#[test]
fn status_outside_a_repository_still_reports() {
    let tree = TempTree::new("status-norepo");
    let output = cloakroom(&tree, &tree.home(), &["status"]);
    let report = stdout(&output);
    assert!(report.contains("repository: none"), "report: {report}");
}

#[test]
fn doctor_is_clean_on_a_healthy_tree() {
    let tree = TempTree::new("doctor-clean");
    tree.write_config(SAMPLE_ALL_USED);
    cloakroom(&tree, &tree.home(), &["init"]);
    let repo = repo(&tree, "src/work/app");

    let output = cloakroom(&tree, &repo, &["doctor"]);
    assert_eq!(
        code(&output),
        0,
        "stdout: {}\nstderr: {}",
        stdout(&output),
        stderr(&output)
    );
    assert!(!stdout(&output).contains("issue:"));
}

#[test]
fn doctor_reports_a_missing_config() {
    let tree = TempTree::new("doctor-missing-config");
    let output = cloakroom(&tree, &tree.home(), &["doctor"]);

    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("no config at"));
}

#[test]
fn doctor_reports_config_parse_errors() {
    let tree = TempTree::new("doctor-parse-error");
    tree.write_config("this is not toml");
    let output = cloakroom(&tree, &tree.home(), &["doctor"]);

    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("invalid config"));
}

#[test]
fn doctor_reports_every_config_validation_error() {
    let tree = TempTree::new("doctor-validation-error");
    tree.write_config(
        "[[rules]]\nprofile = \"missing\"\npath = \"~/src/\"\n\
         [[rules]]\nprofile = \"also-missing\"\nremotes = [\"\"]\n",
    );
    let output = cloakroom(&tree, &tree.home(), &["doctor"]);
    let report = stdout(&output);

    assert_eq!(code(&output), 1, "stdout: {report}");
    assert!(report.contains("unknown profile \"missing\""));
    assert!(report.contains("remote pattern is empty"));
}

#[test]
fn doctor_notes_profiles_without_rules() {
    let tree = TempTree::new("doctor-unused-profile");
    tree.write_config(
        "[profiles.used]\nname = \"Used\"\nemail = \"used@example.com\"\n\
         [profiles.unused]\nname = \"Unused\"\nemail = \"unused@example.com\"\n\
         [[rules]]\nprofile = \"used\"\npath = \"~/src/used/\"\n",
    );
    cloakroom(&tree, &tree.home(), &["init"]);

    let output = cloakroom(&tree, &tree.home(), &["doctor"]);
    assert_eq!(code(&output), 0, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("profile unused has no rules"));
}

#[test]
fn doctor_flags_conditions_that_select_different_profiles() {
    let tree = TempTree::new("doctor-shadowed-condition");
    tree.write_config(
        "[profiles.a]\nname = \"A\"\nemail = \"a@example.com\"\n\
         [profiles.b]\nname = \"B\"\nemail = \"b@example.com\"\n\
         [[rules]]\nprofile = \"a\"\npath = \"~/src/shared/\"\n\
         [[rules]]\nprofile = \"b\"\npath = \"~/src/shared/\"\n",
    );
    cloakroom(&tree, &tree.home(), &["init"]);

    let output = cloakroom(&tree, &tree.home(), &["doctor"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("selects profiles a, b"));
}

#[test]
fn doctor_flags_a_stale_generated_file() {
    let tree = TempTree::new("doctor-stale");
    tree.write_config(SAMPLE_ALL_USED);
    cloakroom(&tree, &tree.home(), &["init"]);
    let root = tree.config_dir().join("generated/root.gitconfig");
    let mut contents = std::fs::read_to_string(&root).unwrap();
    contents.push_str("# hand edit\n");
    std::fs::write(&root, contents).unwrap();

    let output = cloakroom(&tree, &tree.home(), &["doctor"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("generated/root.gitconfig is stale"));
}

#[test]
fn doctor_flags_a_missing_generated_object() {
    let tree = TempTree::new("doctor-missing-object");
    tree.write_config(SAMPLE_ALL_USED);
    cloakroom(&tree, &tree.home(), &["init"]);
    let object = tree.object_containing("pat@work.example");
    std::fs::remove_file(&object).unwrap();

    let output = cloakroom(&tree, &tree.home(), &["doctor"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("is missing; run cloakroom apply"));
}

#[test]
fn doctor_flags_a_missing_managed_include() {
    let tree = TempTree::new("doctor-include");
    tree.write_config(SAMPLE_ALL_USED);
    cloakroom(&tree, &tree.home(), &["init"]);
    git(
        &tree,
        &tree.home(),
        &["config", "--global", "--unset-all", "include.path"],
    );

    let output = cloakroom(&tree, &tree.home(), &["doctor"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("does not include"));
}

#[test]
fn doctor_flags_a_local_identity_override() {
    let tree = TempTree::new("doctor-override");
    tree.write_config(SAMPLE_ALL_USED);
    cloakroom(&tree, &tree.home(), &["init"]);
    let repo = repo(&tree, "src/work/app");
    git(
        &tree,
        &repo,
        &["config", "user.email", "someone@else.example"],
    );

    let output = cloakroom(&tree, &repo, &["doctor"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    let report = stdout(&output);
    assert!(
        report.contains("cloakroom profile work sets \"pat@work.example\""),
        "report: {report}"
    );
}

#[test]
fn doctor_flags_a_local_name_override() {
    let tree = TempTree::new("doctor-name-override");
    tree.write_config(SAMPLE_ALL_USED);
    cloakroom(&tree, &tree.home(), &["init"]);
    let repo = repo(&tree, "src/work/name-override");
    git(&tree, &repo, &["config", "user.name", "Someone Else"]);

    let output = cloakroom(&tree, &repo, &["doctor"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("cloakroom profile work sets \"Pat Work\""));
}

/// An empty config in a sandbox with no system or global identity. Nothing
/// is broken; git has no name or email here, and doctor says so
/// because git will refuse the next commit.
#[test]
fn doctor_reports_missing_identity_fields() {
    let tree = TempTree::new("doctor-missing-identity");
    tree.write_config("");
    cloakroom(&tree, &tree.home(), &["init"]);
    let repo = repo(&tree, "missing-identity/app");

    let output = cloakroom(&tree, &repo, &["doctor"]);
    let report = stdout(&output);
    assert_eq!(code(&output), 1, "stdout: {report}");
    assert!(report.contains("no user.name resolves"));
    assert!(report.contains("no user.email resolves"));
}

#[test]
fn doctor_accepts_a_complete_identity_when_no_rule_matches() {
    let tree = TempTree::new("doctor-foreign-identity");
    tree.write_config("");
    cloakroom(&tree, &tree.home(), &["init"]);
    git(
        &tree,
        &tree.home(),
        &["config", "--global", "user.name", "Pat Global"],
    );
    git(
        &tree,
        &tree.home(),
        &["config", "--global", "user.email", "pat@global.example"],
    );
    let repo = repo(&tree, "foreign-identity/app");

    let output = cloakroom(&tree, &repo, &["doctor"]);
    assert_eq!(code(&output), 0, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("identity comes from elsewhere"));
}

#[test]
fn doctor_rejects_an_external_profile_marker() {
    let tree = TempTree::new("doctor-marker");
    tree.write_config(SAMPLE_ALL_USED);
    cloakroom(&tree, &tree.home(), &["init"]);
    let repo = repo(&tree, "src/work/app");
    git(&tree, &repo, &["config", "cloakroom.profile", "work"]);
    git(&tree, &repo, &["config", "user.name", "Pat Work"]);
    git(&tree, &repo, &["config", "user.email", "pat@work.example"]);

    let output = cloakroom(&tree, &repo, &["doctor"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("not a generated object"));
}

/// The config is rewritten after apply, so the generated files still select
/// work while config.toml no longer defines it. The marker is genuine and the
/// identity is real; only the source has moved on.
#[test]
fn doctor_flags_a_generated_marker_missing_from_the_source() {
    let tree = TempTree::new("doctor-unknown-marker");
    tree.write_config(SAMPLE_ALL_USED);
    cloakroom(&tree, &tree.home(), &["init"]);
    let repo = repo(&tree, "src/work/app");
    tree.write_config(
        "[profiles.personal]\nname = \"Pat Personal\"\nemail = \"pat@example.com\"\n\
         [[rules]]\nprofile = \"personal\"\npath = \"~/src/work/\"\n",
    );

    let output = cloakroom(&tree, &repo, &["doctor"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("profile marker \"work\" is not in config.toml"));
}

/// A broken config does not stop the already generated files from selecting
/// an identity. Doctor has to keep going and report, not stop at the config.
#[test]
fn doctor_still_checks_a_selected_identity_when_the_config_is_invalid() {
    let tree = TempTree::new("doctor-invalid-selected");
    tree.write_config(SAMPLE_ALL_USED);
    cloakroom(&tree, &tree.home(), &["init"]);
    let repo = repo(&tree, "src/work/invalid-source");
    tree.write_config("[[rules]]\nprofile = \"missing\"\npath = \"~/src/\"\n");

    let output = cloakroom(&tree, &repo, &["doctor"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("unknown profile"));
}

/// The publish order under failure. A directory is created where the new
/// object file has to go, which makes that write fail with the config already
/// validated. The root must still be the previous one, because a root naming
/// an object that does not exist is a gitconfig git cannot read.
#[test]
fn apply_keeps_the_previous_root_when_an_object_write_fails() {
    let tree = TempTree::new("publish-failure");
    tree.write_config(SAMPLE);
    let output = cloakroom(&tree, &tree.home(), &["apply"]);
    assert_eq!(code(&output), 0, "stderr: {}", stderr(&output));
    let root_before = tree.read_generated("root.gitconfig");

    let changed = SAMPLE.replace("name = \"Pat Work\"", "name = \"New Work\"");
    tree.write_config(&changed);
    let changed_object = GOLDEN_WORK_PROFILE.replace("Pat Work", "New Work");
    let blocked = tree
        .config_dir()
        .join("generated/objects")
        .join(format!("{}.gitconfig", digest(&changed_object)));
    std::fs::create_dir(&blocked).unwrap();

    let output = cloakroom(&tree, &tree.home(), &["apply"]);
    assert_eq!(code(&output), 2, "stdout: {}", stdout(&output));
    assert_eq!(tree.read_generated("root.gitconfig"), root_before);
}

#[test]
fn status_flags_a_name_override_on_a_selected_profile() {
    let tree = TempTree::new("status-name-override");
    tree.write_config(SAMPLE_ALL_USED);
    cloakroom(&tree, &tree.home(), &["init"]);
    let repo = repo(&tree, "src/work/app");
    git(&tree, &repo, &["config", "user.name", "Different Name"]);

    let output = cloakroom(&tree, &repo, &["status"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(
        stdout(&output).contains("work selected, but the identity is overridden"),
        "stdout: {}",
        stdout(&output)
    );
}

/// Why the marker exists. Two profiles share an email, so the identity alone
/// cannot say which rule matched, and status still names b.
#[test]
fn profile_marker_distinguishes_profiles_that_share_an_email() {
    let tree = TempTree::new("shared-email");
    tree.write_config(
        "[profiles.a]\nname = \"A\"\nemail = \"same@example.com\"\n\
         [profiles.b]\nname = \"B\"\nemail = \"same@example.com\"\n\
         [[rules]]\nprofile = \"a\"\npath = \"~/src/a/\"\n\
         [[rules]]\nprofile = \"b\"\npath = \"~/src/b/\"\n",
    );
    cloakroom(&tree, &tree.home(), &["init"]);
    let repo = repo(&tree, "src/b/app");

    let output = cloakroom(&tree, &repo, &["status"]);
    assert_eq!(code(&output), 0, "stderr: {}", stderr(&output));
    let report = stdout(&output);
    assert!(
        report.contains("identity:   B <same@example.com>"),
        "{report}"
    );
    assert!(
        report.contains("profile:    b (selected by cloakroom)"),
        "{report}"
    );
}

#[test]
fn status_requires_both_identity_fields() {
    let tree = TempTree::new("status-partial");
    git(
        &tree,
        &tree.home(),
        &["config", "--global", "user.email", "only@example.com"],
    );
    let repo = repo(&tree, "partial/app");

    let output = cloakroom(&tree, &repo, &["status"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("user.name is not set"));
}

#[test]
fn status_reports_a_missing_email() {
    let tree = TempTree::new("status-name-only");
    git(
        &tree,
        &tree.home(),
        &["config", "--global", "user.name", "Only Name"],
    );
    let repo = repo(&tree, "name-only/app");

    let output = cloakroom(&tree, &repo, &["status"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("user.email is not set"));
}

/// Two files dropped into objects/: a stray gitconfig, which is reported
/// because it is a [user] block an old root could still include, and a
/// README, which is not cloakroom's to judge and must be left alone.
#[test]
fn doctor_flags_an_unreferenced_object() {
    let tree = TempTree::new("doctor-object");
    tree.write_config(SAMPLE_ALL_USED);
    cloakroom(&tree, &tree.home(), &["init"]);
    std::fs::write(
        tree.config_dir().join("generated/objects/unused.gitconfig"),
        "",
    )
    .unwrap();
    std::fs::write(tree.config_dir().join("generated/objects/README"), "").unwrap();

    let output = cloakroom(&tree, &tree.home(), &["doctor"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("not in the current manifest"));
}

/// A valueless key anywhere in the user's gitconfig used to abort every
/// report, because cloakroom reads one `git config --list` for all of them.
/// The key is unrelated to the identity, so the identity must still resolve.
#[test]
fn reports_survive_a_valueless_key_in_the_gitconfig() {
    let tree = TempTree::new("valueless-key");
    tree.write_config(SAMPLE_ALL_USED);
    cloakroom(&tree, &tree.home(), &["init"]);
    let repo = repo(&tree, "src/work/app");
    // git config refuses to write a valueless key, so the global gitconfig
    // is replaced by hand. The include init added goes back in with it.
    std::fs::write(
        tree.home().join(".gitconfig"),
        format!(
            "[pull]\n\trebase\n[include]\n\tpath = {}\n",
            expected_include_path(&tree)
        ),
    )
    .unwrap();

    let output = cloakroom(&tree, &repo, &["status"]);
    assert_eq!(code(&output), 0, "stderr: {}", stderr(&output));
    assert!(
        stdout(&output).contains("profile:    work (selected by cloakroom)"),
        "stdout: {}",
        stdout(&output)
    );

    let output = cloakroom(&tree, &repo, &["doctor"]);
    assert_eq!(
        code(&output),
        0,
        "stdout: {}\nstderr: {}",
        stdout(&output),
        stderr(&output)
    );
}

/// The same file under two names. Init must see the symlinked include as the
/// one it would add and leave the gitconfig alone, and doctor must count the
/// two spellings as two includes of one root once both are present. Unix
/// only, for the symlink.
#[cfg(unix)]
#[test]
fn equivalent_include_targets_are_not_duplicated() {
    use std::os::unix::fs::symlink;

    let tree = TempTree::new("equivalent-include");
    tree.write_config(SAMPLE_ALL_USED);
    cloakroom(&tree, &tree.home(), &["init"]);
    let root = tree.config_dir().join("generated/root.gitconfig");
    let link = tree.config_dir().join("generated/root-link.gitconfig");
    symlink(&root, &link).unwrap();
    git(
        &tree,
        &tree.home(),
        &["config", "--global", "--unset-all", "include.path"],
    );
    git(
        &tree,
        &tree.home(),
        &[
            "config",
            "--global",
            "--add",
            "include.path",
            link.to_str().unwrap(),
        ],
    );

    let output = cloakroom(&tree, &tree.home(), &["init"]);
    assert_eq!(code(&output), 0, "stderr: {}", stderr(&output));
    assert_eq!(global_include_paths(&tree), [link.display().to_string()]);

    git(
        &tree,
        &tree.home(),
        &[
            "config",
            "--global",
            "--add",
            "include.path",
            &expected_include_path(&tree),
        ],
    );
    let output = cloakroom(&tree, &tree.home(), &["doctor"]);
    assert_eq!(code(&output), 1, "stdout: {}", stdout(&output));
    assert!(stdout(&output).contains("includes the generated root 2 times"));
}
