//! Pure compilation of validated config into a deterministic Git config graph.
//!
//! No filesystem, no git, no clock. The same `Config` gives the same bytes
//! every time, which is what lets `apply` report "unchanged" honestly and
//! lets `doctor` check freshness by comparing bytes.
//!
//! Objects are named by the SHA-256 of their own contents. Two profiles that
//! resolve to the same text share one file, and editing a profile writes a
//! new file rather than mutating one git may be reading right now.

use std::collections::BTreeMap;
use std::fmt::Write;

use sha2::{Digest, Sha256};

use crate::config::{Config, Profile, Rule, RuleCondition};

const HEADER: &str = "# Generated by cloakroom. Do not edit.\n\
                      # Edit config.toml and run `cloakroom apply` instead.\n\n";

/// The whole generated tree as text, ready to write. Also the manifest:
/// anything in objects/ whose digest is not a key here is stale.
pub(crate) struct CompiledConfig {
    /// root.gitconfig: includeIf entries and nothing else. Paths in it are
    /// relative to itself, so moving the config directory needs no rewrite.
    pub root: String,
    /// Object contents keyed by their own digest.
    pub objects: BTreeMap<String, String>,
}

/// The includeIf conditions a rule compiles to, in declaration order. A path
/// rule gives one; a remote rule gives one per pattern. Shared with `doctor`,
/// so what it reports is exactly what gets written.
pub(crate) fn conditions(rule: &Rule) -> Vec<String> {
    match &rule.condition {
        RuleCondition::Path {
            path,
            case_insensitive,
        } => {
            let keyword = if *case_insensitive {
                "gitdir/i"
            } else {
                "gitdir"
            };
            vec![format!("{keyword}:{path}")]
        }
        RuleCondition::Remotes { patterns } => patterns
            .iter()
            .map(|pattern| format!("hasconfig:remote.*.url:{pattern}"))
            .collect(),
    }
}

/// Compile every profile to an object, then every rule to includes pointing
/// at those objects.
///
/// Rules are emitted in the order the user wrote them, not in profile order.
/// Git applies the last matching include, so file order is the whole override
/// mechanism and reordering here would silently change which identity wins.
pub(crate) fn compile(config: &Config) -> CompiledConfig {
    let mut object_by_profile = BTreeMap::new();
    let mut objects = BTreeMap::new();

    for (key, profile) in &config.profiles {
        let contents = render_profile(key, profile);
        let digest = digest(&contents);
        object_by_profile.insert(key.as_str(), digest.clone());
        objects.insert(digest, contents);
    }

    let mut root = String::from(HEADER);
    for rule in &config.rules {
        let digest = &object_by_profile[rule.profile.as_str()];
        for condition in conditions(rule) {
            root.push_str(&format!(
                "[includeIf \"{}\"]\n\tpath = ./objects/{digest}.gitconfig\n",
                escape(&condition),
            ));
        }
    }

    CompiledConfig { root, objects }
}

/// One profile's gitconfig.
///
/// The `[cloakroom] profile` marker is what makes reporting possible. It
/// travels with the identity through git's own resolution, so `status` and
/// `doctor` can name the profile that won without reimplementing any
/// matching, and can tell two profiles apart even when they share an email.
/// Its origin also proves the values came from a generated file.
fn render_profile(key: &str, profile: &Profile) -> String {
    format!(
        "{HEADER}[cloakroom]\n\tprofile = \"{}\"\n[user]\n\tname = \"{}\"\n\temail = \"{}\"\n",
        escape(key),
        escape(&profile.name),
        escape(&profile.email)
    )
}

/// Lowercase hex SHA-256. The 64 hex character shape is load bearing:
/// `status::is_generated_marker` uses it to recognize cloakroom's own files.
fn digest(contents: &str) -> String {
    let mut hex = String::with_capacity(64);
    for byte in Sha256::digest(contents.as_bytes()) {
        write!(hex, "{byte:02x}").expect("writing to a String cannot fail");
    }
    hex
}

/// Escape for a double-quoted gitconfig string. Validation already rejected
/// control characters, leaving backslash and quote.
fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{self, RawConfig};

    /// Two profiles where only one has rules, so tests can tell "compiled"
    /// from "referenced".
    fn sample() -> Config {
        let raw: RawConfig = toml::from_str(
            r#"
[profiles.personal]
name = "Pat Personal"
email = "pat@example.com"

[profiles.work]
name = "Pat Work"
email = "pat@work.example"

[[rules]]
profile = "work"
path = "~/src/work/"

[[rules]]
profile = "work"
remotes = [
  "git@example.com:work/**",
  "https://example.com/work/**",
]
"#,
        )
        .unwrap();
        config::validate(raw).unwrap()
    }

    #[test]
    fn compilation_is_deterministic_and_uses_content_addressed_objects() {
        let first = compile(&sample());
        let second = compile(&sample());
        assert_eq!(first.root, second.root);
        assert_eq!(first.objects, second.objects);
        assert_eq!(first.objects.len(), 2);
        for (digest, contents) in &first.objects {
            assert_eq!(digest, &super::digest(contents));
        }
        // Both profiles compile, but only work has rules, so the root names
        // exactly one of them. An unused profile is written, never included.
        assert_eq!(
            first
                .objects
                .keys()
                .filter(|digest| first.root.contains(digest.as_str()))
                .count(),
            1
        );
    }

    #[test]
    fn profile_objects_contain_the_explicit_marker() {
        let compiled = compile(&sample());
        let work = compiled
            .objects
            .values()
            .find(|contents| contents.contains("pat@work.example"))
            .unwrap();
        assert!(work.contains("[cloakroom]\n\tprofile = \"work\""));
        assert!(work.contains("[user]\n\tname = \"Pat Work\""));
    }

    #[test]
    fn case_insensitive_paths_use_the_gitdir_i_keyword() {
        let raw: RawConfig = toml::from_str(
            "[profiles.a]\nname = \"A\"\nemail = \"a@b\"\n[[rules]]\nprofile = \"a\"\npath = \"~/Work/\"\ncase_insensitive = true\n",
        )
        .unwrap();
        let config = config::validate(raw).unwrap();
        assert_eq!(conditions(&config.rules[0]), ["gitdir/i:~/Work/"]);
    }

    #[test]
    fn rules_render_in_toml_order_not_profile_order() {
        let raw: RawConfig = toml::from_str(
            "[profiles.a]\nname = \"A\"\nemail = \"a@b\"\n\
             [profiles.b]\nname = \"B\"\nemail = \"b@b\"\n\
             [[rules]]\nprofile = \"b\"\npath = \"~/b/\"\n\
             [[rules]]\nprofile = \"a\"\npath = \"~/a/\"\n",
        )
        .unwrap();
        let rendered = compile(&config::validate(raw).unwrap()).root;
        let b = rendered.find("gitdir:~/b/").unwrap();
        let a = rendered.find("gitdir:~/a/").unwrap();
        assert!(b < a);
    }

    #[test]
    fn quotes_and_backslashes_are_escaped_in_values() {
        let profile = Profile {
            name: r#"Pat "Slash\" Person"#.to_owned(),
            email: "pat@example.com".to_owned(),
        };
        assert!(render_profile("work", &profile).contains(r#"name = "Pat \"Slash\\\" Person""#));
    }
}
